[package]
name = "xplr"
version = "0.1.8"  # Update app.rs
authors = ["Arijit Basu <sayanarijit@gmail.com>"]
edition = "2018"
description = "An experimental, minimal, configurable TUI file explorer, stealing ideas from nnn and fzf."
license = "MIT"
readme = "README.md"
repository = "https://github.com/sayanarijit/xplr"
homepage = "https://github.com/sayanarijit/xplr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.14", default-features = false, features = ['crossterm', 'serde'] }
termion = "1.5"
crossterm = "0.18"
dirs = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
handlebars = "3.5.3"
shellwords = "1.0.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "navigation"
harness = false
